language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
script: python setup.py test
notifications:
  slack:
    secure: BXKZ/IrvDQrLjkBTp1VxtGxE+Spn6lD44px8x4DVIGz9bUtdhsIDrFXh/V2HezHUaMrzmflp6kxeen/xMuZdedjepPavir99tYM1j8qc6wRVmxTrKkxwiBhlIHlsdgiG5/JQSQ7YoihJIx9n35WiAdFwhJcrsA8fgnCxfN+2E/8=
    rooms:
      secure: PWEOTBpi0BzVB0hVtvdsozLFYEUzd2Umbd+E2QQZLtv88Iysk/dMD508Kn2IcpGOacXQFuAOMKCZkgeaavTr/tygUAq9T/1iMxTiYVK0USR92BGjQ6sN1COo03rTKC/cRpOeX531JbxkrYqR8J1NDco6mZspJPUApF3h/84aw+w=
